import {
  UserProfile,
  CarbonListing,
  BuyerRequirement,
  MatchRecord,
  SupplyRequest,
  Deal,
  LogisticsShipment,
  AppNotification,
} from '@/types';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user-supplier-1',
    name: 'Rajesh Sharma',
    email: 'rajesh@mumbaisteel.com',
    company: 'Mumbai Steel Works',
    role: 'SUPPLIER',
    location: 'Mumbai, Maharashtra',
    latitude: 19.076,
    longitude: 72.8777,
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'user-buyer-1',
    name: 'Dr. Ananya Roy',
    email: 'ananya@greenfuel.in',
    company: 'GreenFuel Technologies',
    role: 'BUYER',
    location: 'Pune, Maharashtra',
    latitude: 18.5204,
    longitude: 73.8567,
    createdAt: '2026-08-05T11:30:00Z',
  },
  {
    id: 'user-admin-1',
    name: 'CarbonX System Admin',
    email: 'admin@carbonx.io',
    company: 'CarbonX Operations',
    role: 'ADMIN',
    location: 'Mumbai, Maharashtra',
    latitude: 19.076,
    longitude: 72.8777,
    createdAt: '2026-01-01T00:00:00Z',
  },
];

export const INITIAL_LISTINGS: CarbonListing[] = [
  {
    id: 'listing-1',
    supplier_id: 'user-supplier-1',
    supplier_name: 'Mumbai Steel Works',
    title: 'Captured CO₂ from Blast Furnace Scrubbing',
    source_type: 'Steel',
    location: 'Mumbai, Maharashtra',
    latitude: 19.076,
    longitude: 72.8777,
    available_quantity: 500,
    unit: 'tonnes/month',
    purity: 99.2,
    capture_method: 'Amine-Based Solvent Absorption',
    temperature: '35°C',
    pressure: '2.5 bar',
    availability_date: '2026-10-01',
    price_per_tonne: 4500,
    status: 'ACTIVE',
    created_at: '2026-08-10T09:00:00Z',
    updated_at: '2026-08-10T09:00:00Z',
  },
  {
    id: 'listing-2',
    supplier_id: 'user-supplier-2',
    supplier_name: 'Gujarat Cement Infrastructure',
    title: 'Flue Gas CO₂ Recovery Unit',
    source_type: 'Cement',
    location: 'Ahmedabad, Gujarat',
    latitude: 23.0225,
    longitude: 72.5714,
    available_quantity: 800,
    unit: 'tonnes/month',
    purity: 96.5,
    capture_method: 'Calcium Looping Process',
    temperature: '40°C',
    pressure: '1.8 bar',
    availability_date: '2026-10-01',
    price_per_tonne: 3800,
    status: 'ACTIVE',
    created_at: '2026-08-12T14:20:00Z',
    updated_at: '2026-08-12T14:20:00Z',
  },
  {
    id: 'listing-3',
    supplier_id: 'user-supplier-3',
    supplier_name: 'Maharashtra Power Corp',
    title: 'Thermal Power Plant Post-Combustion CO₂',
    source_type: 'Power',
    location: 'Nashik, Maharashtra',
    latitude: 19.9975,
    longitude: 73.7898,
    available_quantity: 1200,
    unit: 'tonnes/month',
    purity: 98.0,
    capture_method: 'Chilled Ammonia Process',
    temperature: '25°C',
    pressure: '3.0 bar',
    availability_date: '2026-10-15',
    price_per_tonne: 3200,
    status: 'ACTIVE',
    created_at: '2026-08-15T08:10:00Z',
    updated_at: '2026-08-15T08:10:00Z',
  },
  {
    id: 'listing-4',
    supplier_id: 'user-supplier-4',
    supplier_name: 'Pune Chemical Industries',
    title: 'Ultra-Pure Food/Industrial Grade CO₂',
    source_type: 'Chemical',
    location: 'Pune, Maharashtra',
    latitude: 18.5204,
    longitude: 73.8567,
    available_quantity: 350,
    unit: 'tonnes/month',
    purity: 99.8,
    capture_method: 'Cryogenic Distillation',
    temperature: '-20°C',
    pressure: '18 bar',
    availability_date: '2026-09-25',
    price_per_tonne: 5200,
    status: 'ACTIVE',
    created_at: '2026-08-18T16:45:00Z',
    updated_at: '2026-08-18T16:45:00Z',
  },
  {
    id: 'listing-5',
    supplier_id: 'user-supplier-5',
    supplier_name: 'Konkan Refineries',
    title: 'Refinery Hydrogen Unit CO₂ Output',
    source_type: 'Chemical',
    location: 'Raigad, Maharashtra',
    latitude: 18.5158,
    longitude: 73.1822,
    available_quantity: 650,
    unit: 'tonnes/month',
    purity: 99.5,
    capture_method: 'Membrane Separation Technology',
    temperature: '30°C',
    pressure: '5.0 bar',
    availability_date: '2026-10-01',
    price_per_tonne: 4800,
    status: 'ACTIVE',
    created_at: '2026-08-20T11:00:00Z',
    updated_at: '2026-08-20T11:00:00Z',
  },
];

export const INITIAL_REQUIREMENTS: BuyerRequirement[] = [
  {
    id: 'req-1',
    buyer_id: 'user-buyer-1',
    buyer_name: 'GreenFuel Technologies',
    title: 'High-Purity CO₂ for Synthetic E-Fuel Plant',
    application: 'Synthetic Fuel',
    required_quantity: 300,
    required_purity: 99.0,
    location: 'Pune, Maharashtra',
    latitude: 18.5204,
    longitude: 73.8567,
    max_distance: 250,
    max_price: 5000,
    frequency: 'Monthly',
    status: 'ACTIVE',
    created_at: '2026-08-22T10:00:00Z',
  },
  {
    id: 'req-2',
    buyer_id: 'user-buyer-2',
    buyer_name: 'CarbonBuild Solutions',
    title: 'CO₂ Mineralization for Pre-Cast Concrete Block',
    application: 'Construction',
    required_quantity: 450,
    required_purity: 96.0,
    location: 'Mumbai, Maharashtra',
    latitude: 19.076,
    longitude: 72.8777,
    max_distance: 300,
    max_price: 4200,
    frequency: 'Monthly',
    status: 'ACTIVE',
    created_at: '2026-08-24T15:30:00Z',
  },
  {
    id: 'req-3',
    buyer_id: 'user-buyer-3',
    buyer_name: 'AlgaeX Bio-Tech',
    title: 'Bio-fixation CO₂ Supply for Spirulina & Protein',
    application: 'Algae',
    required_quantity: 200,
    required_purity: 97.5,
    location: 'Surat, Gujarat',
    latitude: 21.1702,
    longitude: 72.8311,
    max_distance: 200,
    max_price: 4000,
    frequency: 'Monthly',
    status: 'ACTIVE',
    created_at: '2026-08-26T09:15:00Z',
  },
];

export const INITIAL_MATCHES: MatchRecord[] = [
  {
    id: 'match-1',
    listing_id: 'listing-1',
    requirement_id: 'req-1',
    score: 94,
    quantityScore: 100,
    purityScore: 98,
    distanceScore: 90,
    priceScore: 92,
    applicationScore: 100,
    reasoning: [
      '✓ Quantity compatible (500 t/month available vs 300 t/month required)',
      '✓ Purity exceeds requirement (99.2% purity vs 99.0% min required)',
      '✓ Within preferred distance (150 km away vs 250 km max allowed)',
      '✓ Price within budget (₹4,500/t vs ₹5,000/t budget)',
      '✓ Application compatible (Steel CO₂ optimal for Synthetic Fuel synthesis)',
    ],
    created_at: '2026-08-25T10:00:00Z',
  },
  {
    id: 'match-2',
    listing_id: 'listing-4',
    requirement_id: 'req-1',
    score: 88,
    quantityScore: 100,
    purityScore: 100,
    distanceScore: 98,
    priceScore: 70,
    applicationScore: 95,
    reasoning: [
      '✓ Ultra-high purity (99.8%) exceeds requirement',
      '✓ Extremely close location (Pune to Pune, <20 km)',
      '⚠ Price higher than target budget (₹5,200/t vs ₹5,000/t max)',
    ],
    created_at: '2026-08-25T11:00:00Z',
  },
  {
    id: 'match-3',
    listing_id: 'listing-2',
    requirement_id: 'req-2',
    score: 91,
    quantityScore: 100,
    purityScore: 98,
    distanceScore: 85,
    priceScore: 95,
    applicationScore: 100,
    reasoning: [
      '✓ Ideal cement flue gas CO₂ for concrete curing',
      '✓ Competitive pricing (₹3,800/t)',
      '✓ Reliable bulk volume availability (800 t/month)',
    ],
    created_at: '2026-08-26T12:00:00Z',
  },
];

export const INITIAL_REQUESTS: SupplyRequest[] = [
  {
    id: 'req-sub-101',
    match_id: 'match-1',
    listing_id: 'listing-1',
    requirement_id: 'req-1',
    buyer_id: 'user-buyer-1',
    buyer_name: 'GreenFuel Technologies',
    supplier_id: 'user-supplier-1',
    supplier_name: 'Mumbai Steel Works',
    quantity: 300,
    start_date: '2026-10-01',
    duration_months: 3,
    message: 'We request 300 tonnes/month of 99.2% CO₂ for our synthetic kerosene production facility in Pune.',
    calculated_carbon_value: 1350000,
    calculated_logistics_cost: 18500,
    calculated_total_value: 1368500,
    status: 'PENDING',
    created_at: '2026-09-01T10:00:00Z',
  },
];

export const INITIAL_DEALS: Deal[] = [
  {
    id: 'deal-cx-1042',
    request_id: 'req-sub-100',
    listing_id: 'listing-1',
    requirement_id: 'req-1',
    buyer_id: 'user-buyer-1',
    buyer_name: 'GreenFuel Technologies',
    supplier_id: 'user-supplier-1',
    supplier_name: 'Mumbai Steel Works',
    quantity: 300,
    price_per_tonne: 4500,
    total_carbon_value: 1350000,
    logistics_cost: 18500,
    total_value: 1368500,
    status: 'IN_TRANSIT',
    created_at: '2026-09-02T12:00:00Z',
    updated_at: '2026-09-03T14:00:00Z',
  },
];

export const INITIAL_SHIPMENTS: LogisticsShipment[] = [
  {
    id: 'shipment-1042',
    deal_id: 'deal-cx-1042',
    origin: 'Mumbai Steel Works, Mumbai, MH',
    destination: 'GreenFuel Technologies, Pune, MH',
    distance_km: 150,
    transport_mode: 'CO₂ Tanker (Cryogenic Liquid)',
    estimated_cost: 18500,
    cost_per_tonne: 61.67,
    estimated_delivery_days: 2,
    status: 'IN_TRANSIT',
    tracking_code: 'CX-MH-94021',
    created_at: '2026-09-02T13:00:00Z',
    updated_at: '2026-09-03T14:00:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    user_id: 'user-supplier-1',
    title: 'New Supply Request Received',
    message: 'GreenFuel Technologies requested 300 t/month supply from Mumbai Steel Works.',
    link: '/requests',
    read: false,
    created_at: '2026-09-01T10:00:00Z',
  },
  {
    id: 'notif-2',
    user_id: 'user-buyer-1',
    title: 'Shipment Update',
    message: 'Shipment CX-MH-94021 is now IN TRANSIT from Mumbai to Pune.',
    link: '/shipments',
    read: false,
    created_at: '2026-09-03T14:00:00Z',
  },
];
