import {
  UserProfile,
  CarbonSource,
  BuyerRequirement,
  MatchRecord,
  FacilitatedDeal,
  LogisticsShipment,
  AppNotification,
  AuditLog,
} from '@/types';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user-buyer-demo',
    name: 'Dr. Ananya Roy',
    email: 'buyer.demo@carbonx.demo',
    company: 'GreenFuel Technologies',
    role: 'BUYER',
    location: 'Pune, Maharashtra',
    latitude: 18.5204,
    longitude: 73.8567,
    buyerProfile: {
      primaryApplication: 'Synthetic Fuel',
      monthlyRequirement: 300,
      requiredPurity: 99.0,
      preferredLocation: 'Pune, Maharashtra',
    },
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'user-dealer-demo',
    name: 'Marcus Vance',
    email: 'dealer.demo@carbonx.demo',
    company: 'CarbonBridge Brokers',
    role: 'DEALER',
    location: 'Mumbai, Maharashtra',
    latitude: 19.076,
    longitude: 72.8777,
    dealerProfile: {
      organizationType: 'Marketplace Brokerage',
      operatingRegion: 'Western India / MH & GJ',
      expectedMonthlyVolume: 2500,
    },
    createdAt: '2026-08-02T11:00:00Z',
  },
  {
    id: 'user-logistics-demo',
    name: 'Captain Ramesh Patel',
    email: 'logistics.demo@carbonx.demo',
    company: 'EcoTransit Logistics',
    role: 'LOGISTICS_PROVIDER',
    location: 'Navi Mumbai, Maharashtra',
    latitude: 19.033,
    longitude: 73.0297,
    logisticsProfile: {
      transportType: 'Cryogenic Tanker Fleet',
      fleetSize: 18,
      serviceRegion: 'Interstate Transport',
      co2TransportCapability: true,
    },
    createdAt: '2026-08-03T09:30:00Z',
  },
];

// Marketplace Supply Entities (NOT authenticated users)
export const INITIAL_SOURCES: CarbonSource[] = [
  {
    id: 'source-1',
    company_name: 'Mumbai Steel Works',
    facility_name: 'Blast Furnace Carbon Capture Unit #1',
    industry: 'Steel',
    location: 'Mumbai, Maharashtra',
    latitude: 19.076,
    longitude: 72.8777,
    available_quantity: 500,
    unit: 'tonnes/month',
    purity: 99.2,
    capture_method: 'Amine-Based Solvent Absorption',
    temperature: '35°C',
    pressure: '2.5 bar',
    price_per_tonne: 4200,
    availability_date: '2026-10-01',
    verification_status: 'VERIFIED',
    created_at: '2026-08-10T09:00:00Z',
    updated_at: '2026-08-10T09:00:00Z',
  },
  {
    id: 'source-2',
    company_name: 'Gujarat Cement Industries',
    facility_name: 'Flue Gas CO₂ Recovery Plant',
    industry: 'Cement',
    location: 'Ahmedabad, Gujarat',
    latitude: 23.0225,
    longitude: 72.5714,
    available_quantity: 800,
    unit: 'tonnes/month',
    purity: 96.5,
    capture_method: 'Calcium Looping Process',
    temperature: '40°C',
    pressure: '1.8 bar',
    price_per_tonne: 3800,
    availability_date: '2026-10-01',
    verification_status: 'VERIFIED',
    created_at: '2026-08-12T14:20:00Z',
    updated_at: '2026-08-12T14:20:00Z',
  },
  {
    id: 'source-3',
    company_name: 'Maharashtra Power Systems',
    facility_name: 'Thermal Power Post-Combustion Unit',
    industry: 'Power',
    location: 'Nashik, Maharashtra',
    latitude: 19.9975,
    longitude: 73.7898,
    available_quantity: 1200,
    unit: 'tonnes/month',
    purity: 98.0,
    capture_method: 'Chilled Ammonia Process',
    temperature: '25°C',
    pressure: '3.0 bar',
    price_per_tonne: 3200,
    availability_date: '2026-10-15',
    verification_status: 'CERTIFIED',
    created_at: '2026-08-15T08:10:00Z',
    updated_at: '2026-08-15T08:10:00Z',
  },
  {
    id: 'source-4',
    company_name: 'Rajasthan Chemical Refineries',
    facility_name: 'Hydrogen Unit High-Purity CO₂ Line',
    industry: 'Chemical',
    location: 'Kota, Rajasthan',
    latitude: 25.2138,
    longitude: 75.8648,
    available_quantity: 350,
    unit: 'tonnes/month',
    purity: 99.8,
    capture_method: 'Cryogenic Distillation',
    temperature: '-20°C',
    pressure: '18 bar',
    price_per_tonne: 5200,
    availability_date: '2026-09-25',
    verification_status: 'VERIFIED',
    created_at: '2026-08-18T16:45:00Z',
    updated_at: '2026-08-18T16:45:00Z',
  },
];

export const INITIAL_REQUIREMENTS: BuyerRequirement[] = [
  {
    id: 'req-1',
    buyer_id: 'user-buyer-demo',
    buyer_name: 'GreenFuel Technologies',
    title: 'High-Purity CO₂ for Synthetic E-Fuel Plant',
    application: 'Synthetic Fuel',
    required_quantity: 300,
    required_purity: 99.0,
    location: 'Pune, Maharashtra',
    latitude: 18.5204,
    longitude: 73.8567,
    max_distance: 250,
    max_price: 5000,
    frequency: 'Monthly',
    status: 'ACTIVE',
    created_at: '2026-08-22T10:00:00Z',
  },
  {
    id: 'req-2',
    buyer_id: 'user-buyer-2',
    buyer_name: 'CarbonBuild Solutions',
    title: 'CO₂ Mineralization for Pre-Cast Concrete Block',
    application: 'Construction',
    required_quantity: 450,
    required_purity: 96.0,
    location: 'Mumbai, Maharashtra',
    latitude: 19.076,
    longitude: 72.8777,
    max_distance: 300,
    max_price: 4200,
    frequency: 'Monthly',
    status: 'ACTIVE',
    created_at: '2026-08-24T15:30:00Z',
  },
];

export const INITIAL_MATCHES: MatchRecord[] = [
  {
    id: 'match-1',
    carbon_source_id: 'source-1',
    requirement_id: 'req-1',
    score: 94,
    quantityScore: 100,
    purityScore: 98,
    distanceScore: 90,
    priceScore: 92,
    applicationScore: 100,
    reasoning: [
      '✓ Quantity compatible (500 t/mo available vs 300 t/mo required)',
      '✓ Purity exceeds requirement (99.2% purity vs 99.0% min required)',
      '✓ Within preferred distance (150 km away vs 250 km max allowed)',
      '✓ Price within budget (₹4,200/t vs ₹5,000/t budget)',
      '✓ Application compatible (Steel CO₂ optimal for Synthetic Fuel synthesis)',
    ],
    created_at: '2026-08-25T10:00:00Z',
  },
  {
    id: 'match-2',
    carbon_source_id: 'source-2',
    requirement_id: 'req-2',
    score: 91,
    quantityScore: 100,
    purityScore: 98,
    distanceScore: 85,
    priceScore: 95,
    applicationScore: 100,
    reasoning: [
      '✓ Ideal cement flue gas CO₂ for concrete curing',
      '✓ Competitive pricing (₹3,800/t)',
      '✓ Reliable bulk volume availability (800 t/month)',
    ],
    created_at: '2026-08-26T12:00:00Z',
  },
];

export const INITIAL_DEALS: FacilitatedDeal[] = [
  {
    id: 'deal-cx-1042',
    dealer_id: 'user-dealer-demo',
    dealer_name: 'CarbonBridge Brokers',
    buyer_id: 'user-buyer-demo',
    buyer_name: 'GreenFuel Technologies',
    carbon_source_id: 'source-1',
    carbon_source_name: 'Mumbai Steel Works',
    requirement_id: 'req-1',
    quantity: 300,
    price_per_tonne: 4200,
    total_carbon_value: 1260000,
    logistics_cost: 18500,
    total_value: 1278500,
    match_score: 94,
    commission: 63000, // 5% of commodity value
    status: 'PROPOSED',
    created_at: '2026-09-02T12:00:00Z',
    updated_at: '2026-09-03T14:00:00Z',
  },
];

export const INITIAL_SHIPMENTS: LogisticsShipment[] = [
  {
    id: 'shipment-cx-2048',
    deal_id: 'deal-cx-1042',
    logistics_provider_id: undefined,
    logistics_provider_name: undefined,
    origin: 'Mumbai Steel Works, Mumbai, MH',
    destination: 'GreenFuel Technologies, Pune, MH',
    distance_km: 150,
    quantity: 300,
    transport_mode: 'CO₂ Tanker (Cryogenic Liquid)',
    vehicle_type: '28-Tonne Cryogenic Semi-Trailer',
    driver_name: 'Unassigned',
    estimated_cost: 18500,
    cost_per_tonne: 61.67,
    estimated_delivery_days: 2,
    status: 'AWAITING_LOGISTICS',
    tracking_code: 'CX-MH-94021',
    tracking_notes: ['Shipment initialized and awaiting logistics provider acceptance'],
    created_at: '2026-09-02T13:00:00Z',
    updated_at: '2026-09-03T14:00:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    user_id: 'user-dealer-demo',
    role_target: 'DEALER',
    title: 'High-Value Match Discovered',
    message: 'Mumbai Steel Works matched GreenFuel Technologies with 94% compatibility.',
    link: '/dashboard/dealer',
    read: false,
    created_at: '2026-09-01T10:00:00Z',
  },
  {
    id: 'notif-2',
    user_id: 'user-buyer-demo',
    role_target: 'BUYER',
    title: 'Dealer Proposal Received',
    message: 'CarbonBridge Brokers proposed 300 t/mo agreement with Mumbai Steel Works.',
    link: '/dashboard/buyer',
    read: false,
    created_at: '2026-09-02T12:30:00Z',
  },
  {
    id: 'notif-3',
    user_id: 'user-logistics-demo',
    role_target: 'LOGISTICS_PROVIDER',
    title: 'New Shipment Opportunity',
    message: 'Shipment #CX-2048 (Mumbai → Pune, 300t CO₂) is available for acceptance.',
    link: '/dashboard/logistics',
    read: false,
    created_at: '2026-09-02T13:10:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-1',
    user_id: 'user-buyer-demo',
    user_name: 'Dr. Ananya Roy',
    role: 'BUYER',
    action: 'CREATE_REQUIREMENT',
    resource: 'Buyer Requirement #req-1 (300 t/mo, 99% purity)',
    timestamp: '2026-08-22T10:00:00Z',
  },
  {
    id: 'audit-2',
    user_id: 'user-dealer-demo',
    user_name: 'Marcus Vance',
    role: 'DEALER',
    action: 'CREATE_PROPOSAL',
    resource: 'Deal Proposal #deal-cx-1042 (94% Match)',
    timestamp: '2026-09-02T12:00:00Z',
  },
];
